import matplotlib.pyplot as plt
import numpy as np
import scipy.stats

def gen_t_variable( n ) : 
  # Your code to generate the variable that we introduced in the previous task goes here
  

# This generates the midpoints of all your histogram bins
nbins, xmin, xmax = 10, -6, 6 
delx = (xmax - xmin ) / nbins
xvals, counts = np.zeros(nbins), np.zeros(nbins)
for i in range(nbins) : xvals[i] = xmin + i*delx

# Add code to generate the histogram here 




# You should not need to modify anything from here onwards
# This plots the probability density function that the central 
# limit theorem predicts for a sample mean computed from 5 standard normal random 
# variables
xvals2 = np.linspace( xmin, xmax, 200 )
yvals = scipy.stats.norm.pdf( xvals2, loc=0, scale=1/np.sqrt(5) )
plt.plot( xvals2, yvals, 'b-' )
# This will plot the histogram that you have generated by sampling the distribution
# that was introduced in the previous task.
plt.plot( xvals, counts, 'r-')
plt.savefig("histogram_t.png")
